version: '3'

services:
  grata_web:
    build: .
    command: bash -c "
      python -u jsons/sectors_json_main.py &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - .:/db.sqlite3
    ports:
      - "8000:8000"