# Generated by Django 2.1.4 on 2018-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('ramal', models.CharField(max_length=4)),
                ('sector', models.CharField(max_length=42)),
                ('email', models.CharField(max_length=25)),
                ('permission', models.CharField(max_length=11)),
            ],
        ),
    ]
