# Generated by Django 2.1.4 on 2019-01-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_questionnaires_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='questionnaires_meeting',
        ),
    ]
