# Generated by Django 2.1.4 on 2018-12-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('meetings', '0002_auto_20181221_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='clients',
            field=models.ManyToManyField(to='clients.Client'),
        ),
    ]
